apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-sample
  labels:
    app: react-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-sample
  template:
    metadata:
      labels:
        app: react-sample
    spec:
      containers:
      - name: react-sample
        image: dockersamples/static-site
        ports:
        - containerPort: 80
        env:
        - name: AUTHOR
          value: "K3s Practice"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
