apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-sample
  labels:
    app: dotnet-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-sample
  template:
    metadata:
      labels:
        app: dotnet-sample
    spec:
      containers:
      - name: dotnet-sample
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
